# created by n9nes												#
# feel free to star the rep - https://github.com/nin9s/elk-hole	#
#################################################################

filebeat.modules:
- module: logstash

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /mnt/entechlog/pihole/var/log/pihole.log

name: elk-hole

output.logstash:
  enabled: true
  hosts: ["ls01:5044"]
