version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

  ls01:
    image: docker.elastic.co/logstash/logstash:7.9.1
    container_name: ls01
    volumes:
      - data04:/usr/share/logstash/data
      - './logstash/conf.d/10-pihole.conf:/usr/share/logstash/pipeline/logstash.conf'
      - './logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro'
    ports:
      - 5000:5000/tcp
      - 5000:5000/udp
      - 9600:9600
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic
      
  fb01:
    image: docker.elastic.co/beats/filebeat:7.9.1
    container_name: fb01
    user: root
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
      KIBANA_HOST: http://kib01:5601
    volumes:
      - data05:/usr/share/filebeat/data
      - '/mnt/entechlog/pihole/var/log/:/mnt/entechlog/pihole/var/log/'
      - './filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:rw'
    networks:
      - elastic
      
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  data04:
    driver: local
  data05:
    driver: local
    
networks:
  elastic:
    driver: bridge