filebeat.modules:
- module: logstash

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /mnt/entechlog/pihole/var/log/pihole.log

name: elk-pihole

output.logstash:
  enabled: true
  hosts: ["ls01:5044"]

#output.elasticsearch:
#  hosts: ["es01:9200"]
#  index: "pihole-raw-%{+YYYY.MM}"

#setup.template.settings:
#  index.number_of_shards: 1

#setup.template:
#  enabled: true
#  name: "pihole-raw"
#  pattern: "pihole-raw-*"

#setup.ilm.enabled: auto
#setup.ilm.rollover_alias: "pihole-raw"
#setup.ilm.pattern: "{now/d}-000001"

processors:
  - add_tags:
      tags: [pihole]
